/* AUTOGENERATED by fw/arm/scripts/gen_golden_header.py — do not hand-edit. */
/* Source: python_multilayer/results_multilayer/fashion_multilayer_golden/ */
#ifndef GOLDEN_FASHION10_H
#define GOLDEN_FASHION10_H

#include <stdint.h>

#define GOLDEN_S0_IN_DIM   196u
#define GOLDEN_S0_OUT_DIM  64u
#define GOLDEN_S1_IN_DIM   64u
#define GOLDEN_S1_OUT_DIM  10u
#define GOLDEN_T           64u
#define GOLDEN_WORDS_PER_ROW 8u
#define GOLDEN_NUM_SAMPLES 10u

/* Packed layout: {neg[7:4], pos[3:0]} per 4-bit pair per byte. */
extern const uint8_t golden_s0_w_packed[196 * 64];
extern const uint8_t golden_s1_w_packed[64 * 10];

/* Raw pos/neg 4-bit arrays (flat row-major, one 4-bit level per byte) —
 * consumed by v2b_load_mac_weights() which takes pos/neg pointers separately. */
extern const uint8_t golden_s0_w_pos[196 * 64];
extern const uint8_t golden_s0_w_neg[196 * 64];
extern const uint8_t golden_s1_w_pos[64 * 10];
extern const uint8_t golden_s1_w_neg[64 * 10];

typedef struct {
    uint8_t  pixel_196[196];                       /* raw uint8 pixels → C1 path */
    uint32_t encoded_stream[64 * 8];    /* pre-encoded WL stream → C0 path */
    int32_t  expected_counts[10];                /* per-class spike counts */
    uint8_t  expected_class;                           /* argmax */
} v2b_fashion_sample_t;

extern const v2b_fashion_sample_t golden_fashion10[10];

#endif /* GOLDEN_FASHION10_H */
