/* AUTOGENERATED by fw/arm/scripts/gen_lenet5_header.py - do not hand-edit. */
#ifndef GOLDEN_LENET5_H
#define GOLDEN_LENET5_H

#include <stdint.h>

#define LENET5_NUM_SAMPLES 10u
#define LENET5_T_COUNT 10u
#define LENET5_INPUT_WORDS 784u
#define LENET5_CONV1_TILE_COUNT 1u
#define LENET5_CONV2_TILE_COUNT 1u
#define LENET5_FC1_TILE_COUNT 9u
#define LENET5_FC2_TILE_COUNT 1u
#define LENET5_FC3_TILE_COUNT 1u

#define LENET5_CONV1_C_OUT 6u
#define LENET5_CONV2_C_OUT 16u
#define LENET5_FC1_C_OUT 120u
#define LENET5_FC2_C_OUT 84u
#define LENET5_FC3_C_OUT 10u

#define LENET5_TH_CONV1 8u
#define LENET5_TH_CONV2 16u
#define LENET5_TH_FC1   7u
#define LENET5_TH_FC2   7u
#define LENET5_TH_FC3   3u

#define LENET5_SUMMAX_CONV1 1023u
#define LENET5_SUMMAX_CONV2 1023u
#define LENET5_SUMMAX_FC1   1023u
#define LENET5_SUMMAX_FC2   1023u
#define LENET5_SUMMAX_FC3   1023u

typedef struct {
    uint32_t input_words[LENET5_INPUT_WORDS];
    int32_t expected_counts[10];
    uint8_t expected_class;
    uint8_t label;
    uint16_t test_index;
} v2b_lenet5_sample_t;

extern const uint16_t lenet5_conv1_offsets[];
extern const uint8_t  lenet5_conv1_entries[];
extern const uint16_t lenet5_conv2_offsets[];
extern const uint8_t  lenet5_conv2_entries[];
extern const uint16_t lenet5_fc1_offsets[];
extern const uint8_t  lenet5_fc1_entries[];
extern const uint16_t lenet5_fc2_offsets[];
extern const uint8_t  lenet5_fc2_entries[];
extern const uint16_t lenet5_fc3_offsets[];
extern const uint8_t  lenet5_fc3_entries[];
extern const v2b_lenet5_sample_t golden_lenet5[LENET5_NUM_SAMPLES];

#endif /* GOLDEN_LENET5_H */
