/* AUTOGENERATED by fw/arm/scripts/gen_golden_fashion28_header.py.
 * Source: python_multilayer/results_multilayer/fashion28_multilayer_golden/
 * Do not hand-edit. */
#ifndef GOLDEN_FASHION28_H
#define GOLDEN_FASHION28_H

#include <stdint.h>

#define GOLDEN_F28_S0_IN_DIM 784u
#define GOLDEN_F28_S0_OUT_DIM 64u
#define GOLDEN_F28_S1_IN_DIM 64u
#define GOLDEN_F28_S1_OUT_DIM 10u
#define GOLDEN_F28_NUM_SAMPLES 10u

extern const uint8_t golden_f28_s0_w_packed[784 * 64];
extern const uint8_t golden_f28_s1_w_packed[64 * 10];

typedef struct {
    uint8_t pixel_784[784];
    uint8_t expected_counts[10];
    uint8_t expected_class;
} v2b_fashion28_sample_t;

extern const v2b_fashion28_sample_t golden_fashion28[10];

#endif /* GOLDEN_FASHION28_H */
