# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/VivadoProject/project_5/project_5.srcs/sources_1/bd/bd_step3_arm/ip/bd_step3_arm_rst_ps8_0_49M_0/bd_step3_arm_rst_ps8_0_49M_0.xci
# IP: The module: 'bd_step3_arm_rst_ps8_0_49M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VivadoProject/project_5/project_5.gen/sources_1/bd/bd_step3_arm/ip/bd_step3_arm_rst_ps8_0_49M_0/bd_step3_arm_rst_ps8_0_49M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_step3_arm_rst_ps8_0_49M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/VivadoProject/project_5/project_5.gen/sources_1/bd/bd_step3_arm/ip/bd_step3_arm_rst_ps8_0_49M_0/bd_step3_arm_rst_ps8_0_49M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_step3_arm_rst_ps8_0_49M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/VivadoProject/project_5/project_5.gen/sources_1/bd/bd_step3_arm/ip/bd_step3_arm_rst_ps8_0_49M_0/bd_step3_arm_rst_ps8_0_49M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_step3_arm_rst_ps8_0_49M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/VivadoProject/project_5/project_5.srcs/sources_1/bd/bd_step3_arm/ip/bd_step3_arm_rst_ps8_0_49M_0/bd_step3_arm_rst_ps8_0_49M_0.xci
# IP: The module: 'bd_step3_arm_rst_ps8_0_49M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VivadoProject/project_5/project_5.gen/sources_1/bd/bd_step3_arm/ip/bd_step3_arm_rst_ps8_0_49M_0/bd_step3_arm_rst_ps8_0_49M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_step3_arm_rst_ps8_0_49M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/VivadoProject/project_5/project_5.gen/sources_1/bd/bd_step3_arm/ip/bd_step3_arm_rst_ps8_0_49M_0/bd_step3_arm_rst_ps8_0_49M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_step3_arm_rst_ps8_0_49M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/VivadoProject/project_5/project_5.gen/sources_1/bd/bd_step3_arm/ip/bd_step3_arm_rst_ps8_0_49M_0/bd_step3_arm_rst_ps8_0_49M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_step3_arm_rst_ps8_0_49M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
