#!/usr/bin/env python3
"""Generate `golden_fashion28.h` + `.c` for Config #5 ARM firmware.

Reads `python_multilayer/results_multilayer/fashion28_multilayer_golden/`,
reloads the class-first Fashion-MNIST 28x28 samples, and emits compact C data:

- packed stage-0 weights: `{neg[7:4], pos[3:0]}` bytes for `784 x 64`
- packed stage-1 weights: `{neg[7:4], pos[3:0]}` bytes for `64 x 10`
- per-sample raw pixels `uint8 pixel_784[784]`
- per-sample expected counts `uint8 expected_counts[10]`
- per-sample expected class
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[3]
PY_ML = ROOT / "python_multilayer"
GOLDEN_DIR = PY_ML / "results_multilayer" / "fashion28_multilayer_golden"
OUT_INC = ROOT / "fw" / "arm" / "include" / "golden_fashion28.h"
OUT_SRC = ROOT / "fw" / "arm" / "src" / "golden_fashion28.c"

S0_IN = 784
S0_OUT = 64
S1_IN = 64
S1_OUT = 10
NUM_SAMPLES = 10


def load_weights_hex(path: Path, rows: int, cols: int) -> np.ndarray:
    with path.open() as f:
        vals = [int(line.strip(), 16) for line in f if line.strip()]
    arr = np.asarray(vals, dtype=np.uint8)
    assert arr.size == rows * cols, f"{path}: got {arr.size} expected {rows * cols}"
    return arr.reshape(rows, cols)


def pack_weights(w_pos: np.ndarray, w_neg: np.ndarray) -> np.ndarray:
    assert w_pos.shape == w_neg.shape
    packed = ((w_neg & 0x0F) << 4) | (w_pos & 0x0F)
    return packed.flatten().astype(np.uint8)


def load_counts(path: Path) -> np.ndarray:
    with path.open() as f:
        vals = [int(line.strip()) for line in f if line.strip()]
    assert len(vals) == S1_OUT
    return np.asarray(vals, dtype=np.uint8)


def load_pixels_for_sample(k: int) -> np.ndarray:
    if str(PY_ML) not in sys.path:
        sys.path.insert(0, str(PY_ML))
    import _vendored_from_v1.data_utils as v1_data  # type: ignore
    import config_multilayer as cfg  # type: ignore

    data_dir = str(cfg.ROOT_DIR / "data")
    x_test, y_test = v1_data.load_fashion_mnist_test(
        data_dir, target_size=28, method="avgpool"
    )
    x = x_test.numpy() if hasattr(x_test, "numpy") else np.asarray(x_test)
    y = y_test.numpy() if hasattr(y_test, "numpy") else np.asarray(y_test)
    if x.ndim == 3:
        x = x.reshape(-1, 28 * 28)
    x = x.astype(np.int64)
    hits = np.where(y == k)[0]
    if len(hits) == 0:
        raise RuntimeError(f"No Fashion-MNIST test sample for class {k}")
    pix = x[int(hits[0])]
    pix = np.clip(pix, 0, 255).astype(np.uint8)
    assert pix.shape == (S0_IN,), f"pixel shape {pix.shape} != ({S0_IN},)"
    return pix


def fmt_uint8_array(arr: np.ndarray, per_line: int = 16) -> str:
    lines = []
    for i in range(0, arr.size, per_line):
        chunk = arr[i:i + per_line]
        lines.append("  " + ", ".join(f"0x{int(v):02x}" for v in chunk) + ",")
    return "\n".join(lines)


def main() -> int:
    if not GOLDEN_DIR.exists():
        print(f"[FATAL] golden dir missing: {GOLDEN_DIR}", file=sys.stderr)
        return 1

    if str(PY_ML) not in sys.path:
        sys.path.insert(0, str(PY_ML))
    from gen_multilayer_fashion28_trace_baseline import compute_config5_board_equivalent  # type: ignore

    s0_pos = load_weights_hex(GOLDEN_DIR / "stage0_w_pos.hex", S0_IN, S0_OUT)
    s0_neg = load_weights_hex(GOLDEN_DIR / "stage0_w_neg.hex", S0_IN, S0_OUT)
    s1_pos = load_weights_hex(GOLDEN_DIR / "stage1_w_pos.hex", S1_IN, S1_OUT)
    s1_neg = load_weights_hex(GOLDEN_DIR / "stage1_w_neg.hex", S1_IN, S1_OUT)

    s0_packed = pack_weights(s0_pos, s0_neg)
    s1_packed = pack_weights(s1_pos, s1_neg)

    samples = []
    for k in range(NUM_SAMPLES):
        _, _, counts_i64, pred, _label = compute_config5_board_equivalent(k)
        counts = counts_i64.astype(np.uint8)
        pixels = load_pixels_for_sample(k)
        samples.append({"pixels": pixels, "counts": counts, "pred": pred})

    OUT_INC.parent.mkdir(parents=True, exist_ok=True)
    OUT_SRC.parent.mkdir(parents=True, exist_ok=True)

    with OUT_INC.open("w", encoding="utf-8", newline="\n") as f:
        f.write(f"""\
/* AUTOGENERATED by fw/arm/scripts/gen_golden_fashion28_header.py.
 * Source: python_multilayer/results_multilayer/fashion28_multilayer_golden/
 * Do not hand-edit. */
#ifndef GOLDEN_FASHION28_H
#define GOLDEN_FASHION28_H

#include <stdint.h>

#define GOLDEN_F28_S0_IN_DIM {S0_IN}u
#define GOLDEN_F28_S0_OUT_DIM {S0_OUT}u
#define GOLDEN_F28_S1_IN_DIM {S1_IN}u
#define GOLDEN_F28_S1_OUT_DIM {S1_OUT}u
#define GOLDEN_F28_NUM_SAMPLES {NUM_SAMPLES}u

extern const uint8_t golden_f28_s0_w_packed[{S0_IN} * {S0_OUT}];
extern const uint8_t golden_f28_s1_w_packed[{S1_IN} * {S1_OUT}];

typedef struct {{
    uint8_t pixel_784[{S0_IN}];
    uint8_t expected_counts[{S1_OUT}];
    uint8_t expected_class;
}} v2b_fashion28_sample_t;

extern const v2b_fashion28_sample_t golden_fashion28[{NUM_SAMPLES}];

#endif /* GOLDEN_FASHION28_H */
""")

    with OUT_SRC.open("w", encoding="utf-8", newline="\n") as f:
        f.write("/* AUTOGENERATED by fw/arm/scripts/gen_golden_fashion28_header.py. */\n")
        f.write('#include "golden_fashion28.h"\n\n')

        f.write(f"const uint8_t golden_f28_s0_w_packed[{S0_IN} * {S0_OUT}] = {{\n")
        f.write(fmt_uint8_array(s0_packed))
        f.write("\n};\n\n")

        f.write(f"const uint8_t golden_f28_s1_w_packed[{S1_IN} * {S1_OUT}] = {{\n")
        f.write(fmt_uint8_array(s1_packed))
        f.write("\n};\n\n")

        f.write(f"const v2b_fashion28_sample_t golden_fashion28[{NUM_SAMPLES}] = {{\n")
        for sample in samples:
            f.write("  {\n")
            f.write("    .pixel_784 = {\n")
            f.write(fmt_uint8_array(sample["pixels"]))
            f.write("\n    },\n")
            f.write("    .expected_counts = {\n")
            f.write(fmt_uint8_array(sample["counts"], per_line=10))
            f.write("\n    },\n")
            f.write(f"    .expected_class = {sample['pred']}u,\n")
            f.write("  },\n")
        f.write("};\n")

    print(f"[gen_golden_fashion28_header] wrote {OUT_INC}")
    print(f"[gen_golden_fashion28_header] wrote {OUT_SRC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
