#!/usr/bin/env python3
"""Generate `fw/v2_e203_smoke/{include,src}/golden_fashion10.{h,c}`.

Reads `python_multilayer/results_multilayer/fashion_multilayer_golden/` weight
hex + per-sample counts, and re-runs Fashion-MNIST avgpool-14x14 pixel
selection via `python_multilayer/_vendored_from_v1/data_utils.py`, then emits
the C data the smoke firmware consumes at runtime.

Layout differences vs arm-demo's `gen_golden_header.py`:
  - NO pre-encoded WL stream in C (v2-e203 smoke CPU runs Bresenham live)
  - NO packed weights (v2b_scheduler.c takes pos/neg pointers separately)
  - Only keeps: stage0 pos/neg 4-bit tables, stage1 pos/neg 4-bit tables,
    per-sample {pixel_196, expected_counts[10], expected_class}.

Run:
  wsl bash -c "cd '/mnt/d/SoC Design/SoC Design/fw/v2_e203_smoke/scripts' && python3 gen_golden_fashion10.py"
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[3]
PY_ML = ROOT / "python_multilayer"
GOLDEN_DIR = PY_ML / "results_multilayer" / "fashion_multilayer_golden"
OUT_INC = ROOT / "fw" / "v2_e203_smoke" / "include" / "golden_fashion10.h"
OUT_SRC = ROOT / "fw" / "v2_e203_smoke" / "src" / "golden_fashion10.c"

S0_IN = 196
S0_OUT = 64
S1_IN = 64
S1_OUT = 10
NUM_SAMPLES = 10


def load_weights_hex(path: Path, rows: int, cols: int) -> np.ndarray:
    with path.open() as f:
        vals = [int(line.strip(), 16) for line in f if line.strip()]
    arr = np.asarray(vals, dtype=np.uint8)
    assert arr.size == rows * cols, f"{path}: got {arr.size} expected {rows*cols}"
    return arr.reshape(rows, cols)


def load_counts(path: Path) -> np.ndarray:
    with path.open() as f:
        vals = [int(line.strip()) for line in f if line.strip()]
    assert len(vals) == S1_OUT
    return np.asarray(vals, dtype=np.int32)


def load_predicted(path: Path) -> int:
    return int(path.read_text().strip())


def load_pixels_for_sample(k: int) -> np.ndarray:
    """Reload Fashion-MNIST test set via v1 vendored loader; pick class-k's first occurrence."""
    if str(PY_ML) not in sys.path:
        sys.path.insert(0, str(PY_ML))
    import _vendored_from_v1.data_utils as v1_data  # type: ignore
    import config_multilayer as cfg  # type: ignore
    data_dir = str(cfg.ROOT_DIR / "data")
    x_test, y_test = v1_data.load_fashion_mnist_test(
        data_dir, target_size=14, method="avgpool"
    )
    x = x_test.numpy() if hasattr(x_test, "numpy") else np.asarray(x_test)
    y = y_test.numpy() if hasattr(y_test, "numpy") else np.asarray(y_test)
    if x.ndim == 3:
        x = x.reshape(-1, 14 * 14)
    x = x.astype(np.int64)
    hits = np.where(y == k)[0]
    if len(hits) == 0:
        raise RuntimeError(f"No Fashion-MNIST test sample for class {k}")
    pix = x[int(hits[0])]
    pix = np.clip(pix, 0, 255).astype(np.uint8)
    assert pix.shape == (S0_IN,), f"pixel shape {pix.shape} != ({S0_IN},)"
    return pix


def fmt_uint8(arr: np.ndarray, per_line: int = 16) -> str:
    out = []
    for i in range(0, arr.size, per_line):
        chunk = arr[i : i + per_line]
        out.append("  " + ", ".join(f"0x{v:02x}" for v in chunk) + ",")
    return "\n".join(out)


def fmt_int32(arr: np.ndarray) -> str:
    return "  " + ", ".join(str(int(v)) for v in arr)


def main() -> int:
    if not GOLDEN_DIR.exists():
        print(f"[FATAL] golden dir missing: {GOLDEN_DIR}", file=sys.stderr)
        return 1

    s0_pos = load_weights_hex(GOLDEN_DIR / "stage0_w_pos.hex", S0_IN, S0_OUT).flatten()
    s0_neg = load_weights_hex(GOLDEN_DIR / "stage0_w_neg.hex", S0_IN, S0_OUT).flatten()
    s1_pos = load_weights_hex(GOLDEN_DIR / "stage1_w_pos.hex", S1_IN, S1_OUT).flatten()
    s1_neg = load_weights_hex(GOLDEN_DIR / "stage1_w_neg.hex", S1_IN, S1_OUT).flatten()

    samples = []
    for k in range(NUM_SAMPLES):
        counts = load_counts(GOLDEN_DIR / f"sample_{k:02d}_counts.txt")
        pred   = load_predicted(GOLDEN_DIR / f"sample_{k:02d}_predicted.txt")
        pixels = load_pixels_for_sample(k)
        samples.append({"pixels": pixels, "counts": counts, "pred": pred})

    OUT_INC.parent.mkdir(parents=True, exist_ok=True)
    OUT_SRC.parent.mkdir(parents=True, exist_ok=True)

    with OUT_INC.open("w", encoding="utf-8", newline="\n") as f:
        f.write(f"""\
/* AUTOGENERATED by fw/v2_e203_smoke/scripts/gen_golden_fashion10.py
 * Source: python_multilayer/results_multilayer/fashion_multilayer_golden/
 * Do not hand-edit. */
#ifndef GOLDEN_FASHION10_H
#define GOLDEN_FASHION10_H

#include <stdint.h>

#define GOLDEN_S0_IN_DIM   {S0_IN}u
#define GOLDEN_S0_OUT_DIM  {S0_OUT}u
#define GOLDEN_S1_IN_DIM   {S1_IN}u
#define GOLDEN_S1_OUT_DIM  {S1_OUT}u
#define GOLDEN_NUM_SAMPLES {NUM_SAMPLES}u

/* 4-bit weight values packed into uint8 (high nibble always zero).
 * Row-major, [in_dim][out_dim] linearised. */
extern const uint8_t golden_s0_w_pos[{S0_IN} * {S0_OUT}];
extern const uint8_t golden_s0_w_neg[{S0_IN} * {S0_OUT}];
extern const uint8_t golden_s1_w_pos[{S1_IN} * {S1_OUT}];
extern const uint8_t golden_s1_w_neg[{S1_IN} * {S1_OUT}];

typedef struct {{
    uint8_t  pixel_196[{S0_IN}];
    int32_t  expected_counts[{S1_OUT}];
    uint8_t  expected_class;
}} v2b_fashion_sample_t;

extern const v2b_fashion_sample_t golden_fashion10[{NUM_SAMPLES}];

#endif /* GOLDEN_FASHION10_H */
""")

    with OUT_SRC.open("w", encoding="utf-8", newline="\n") as f:
        f.write("""\
/* AUTOGENERATED by fw/v2_e203_smoke/scripts/gen_golden_fashion10.py
 * Do not hand-edit. */
#include "golden_fashion10.h"

""")
        f.write(f"const uint8_t golden_s0_w_pos[{S0_IN}*{S0_OUT}] = {{\n{fmt_uint8(s0_pos)}\n}};\n\n")
        f.write(f"const uint8_t golden_s0_w_neg[{S0_IN}*{S0_OUT}] = {{\n{fmt_uint8(s0_neg)}\n}};\n\n")
        f.write(f"const uint8_t golden_s1_w_pos[{S1_IN}*{S1_OUT}] = {{\n{fmt_uint8(s1_pos)}\n}};\n\n")
        f.write(f"const uint8_t golden_s1_w_neg[{S1_IN}*{S1_OUT}] = {{\n{fmt_uint8(s1_neg)}\n}};\n\n")

        f.write(f"const v2b_fashion_sample_t golden_fashion10[{NUM_SAMPLES}] = {{\n")
        for k, s in enumerate(samples):
            f.write(f"  /* sample {k} (predicted class = {s['pred']}) */\n")
            f.write("  {\n")
            f.write("    .pixel_196 = {\n" + fmt_uint8(s["pixels"]) + "\n    },\n")
            f.write("    .expected_counts = {" + fmt_int32(s["counts"]) + "},\n")
            f.write(f"    .expected_class = {s['pred']}u,\n")
            f.write("  },\n")
        f.write("};\n")

    print(f"[OK] wrote {OUT_INC}")
    print(f"[OK] wrote {OUT_SRC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
