#!/usr/bin/env python3
"""Generate compact LeNet-5 golden assets for V2 E203 firmware.

This version is IMEM-friendly:
  - sample inputs are emitted as sparse (word_idx, word_value) pairs
  - weights are emitted as sparse triples: (lane, out_c, packed_posneg)
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
RESULT_DIR = ROOT / "python_multilayer" / "results_conv" / "lenet5"
MANIFEST_PATH = RESULT_DIR / "lenet5_golden_manifest.json"
OUT_HDR = ROOT / "fw" / "v2_e203_smoke" / "include" / "golden_lenet5.h"
OUT_SRC = ROOT / "fw" / "v2_e203_smoke" / "src" / "golden_lenet5.c"


def read_hex_lines(path: Path) -> list[int]:
    return [int(line.strip(), 16) for line in path.read_text(encoding="ascii").splitlines() if line.strip()]


def read_counts(path: Path) -> list[int]:
    counts = [0] * 10
    for line in path.read_text(encoding="ascii").splitlines():
        line = line.strip()
        if not line:
            continue
        idx_s, val_s = line.split()
        counts[int(idx_s)] = int(val_s)
    return counts


def fmt_u8_array(data: list[int], per_line: int = 16) -> str:
    out = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        out.append("  " + ", ".join(f"0x{v:02x}" for v in chunk) + ",")
    return "\n".join(out)


def fmt_u16_array(data: list[int], per_line: int = 12) -> str:
    out = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        out.append("  " + ", ".join(f"{v}u" for v in chunk) + ",")
    return "\n".join(out)


def fmt_u32_array(data: list[int], per_line: int = 8) -> str:
    out = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        out.append("  " + ", ".join(f"0x{v:08x}" for v in chunk) + ",")
    return "\n".join(out)


def collect_sparse_entries(layer: dict) -> tuple[list[int], list[int]]:
    weights_dir = RESULT_DIR / "weights"
    offsets = [0]
    entries: list[int] = []
    for tile in layer["weights"]:
        pos = read_hex_lines(weights_dir / Path(tile["pos"]).name)
        neg = read_hex_lines(weights_dir / Path(tile["neg"]).name)
        c_out = int(layer["C_out"])
        for idx, (p, n) in enumerate(zip(pos, neg)):
            if p == 0 and n == 0:
                continue
            lane = idx // c_out
            out_c = idx % c_out
            packed = ((n & 0xF) << 4) | (p & 0xF)
            entries.extend([lane & 0xFF, out_c & 0xFF, packed & 0xFF])
        offsets.append(len(entries) // 3)
    return offsets, entries


def emit_sparse_arrays(src, layer: dict, layer_name: str) -> tuple[int, int]:
    offsets, entries = collect_sparse_entries(layer)
    src.write(
        f"const uint16_t lenet5_{layer_name}_offsets[{len(offsets)}] = {{\n"
        f"{fmt_u16_array(offsets)}\n"
        "};\n\n"
    )
    src.write(
        f"const uint8_t lenet5_{layer_name}_entries[{len(entries)}] = {{\n"
        f"{fmt_u8_array(entries)}\n"
        "};\n\n"
    )
    return len(offsets), len(entries)


def collect_sparse_inputs(samples: list[dict]) -> tuple[list[int], list[int], list[tuple[int, int, list[int], int, int, int]]]:
    indices: list[int] = []
    words: list[int] = []
    meta: list[tuple[int, int, list[int], int, int, int]] = []
    offset = 0
    for sample in samples:
        input_words = read_hex_lines(RESULT_DIR / sample["input_fmap_words"])
        counts = read_counts(RESULT_DIR / sample["output_counts"])
        sample_indices = []
        sample_words = []
        for idx, value in enumerate(input_words):
            if value == 0:
                continue
            sample_indices.append(idx)
            sample_words.append(value)
        indices.extend(sample_indices)
        words.extend(sample_words)
        meta.append((
            offset,
            len(sample_indices),
            counts,
            int(sample["pred"]),
            int(sample["label"]),
            int(sample["test_index"]),
        ))
        offset += len(sample_indices)
    return indices, words, meta


def main() -> int:
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="ascii"))
    layers = {layer["name"]: layer for layer in manifest["layers"]}
    samples = manifest["samples"]
    num_samples = len(samples)
    input_words_per_sample = len(read_hex_lines(RESULT_DIR / samples[0]["input_fmap_words"]))

    sparse_inputs_idx, sparse_inputs_words, sample_meta = collect_sparse_inputs(samples)

    OUT_HDR.parent.mkdir(parents=True, exist_ok=True)
    OUT_SRC.parent.mkdir(parents=True, exist_ok=True)

    with OUT_HDR.open("w", encoding="ascii", newline="\n") as hdr:
        hdr.write(
            "/* AUTOGENERATED by fw/v2_e203_smoke/scripts/gen_lenet5_header.py - do not hand-edit. */\n"
            "#ifndef GOLDEN_LENET5_H\n"
            "#define GOLDEN_LENET5_H\n\n"
            "#include <stdint.h>\n\n"
            f"#define LENET5_NUM_SAMPLES {num_samples}u\n"
            f"#define LENET5_T_COUNT {int(manifest['t_count'])}u\n"
            f"#define LENET5_INPUT_WORDS {input_words_per_sample}u\n"
            f"#define LENET5_TOTAL_INPUT_NZ {len(sparse_inputs_idx)}u\n"
            f"#define LENET5_CONV1_TILE_COUNT {layers['conv1']['tile_count']}u\n"
            f"#define LENET5_CONV2_TILE_COUNT {layers['conv2']['tile_count']}u\n"
            f"#define LENET5_FC1_TILE_COUNT {layers['fc1']['tile_count']}u\n"
            f"#define LENET5_FC2_TILE_COUNT {layers['fc2']['tile_count']}u\n"
            f"#define LENET5_FC3_TILE_COUNT {layers['fc3']['tile_count']}u\n\n"
            f"#define LENET5_CONV1_C_OUT {layers['conv1']['C_out']}u\n"
            f"#define LENET5_CONV2_C_OUT {layers['conv2']['C_out']}u\n"
            f"#define LENET5_FC1_C_OUT {layers['fc1']['C_out']}u\n"
            f"#define LENET5_FC2_C_OUT {layers['fc2']['C_out']}u\n"
            f"#define LENET5_FC3_C_OUT {layers['fc3']['C_out']}u\n\n"
            f"#define LENET5_TH_CONV1 {layers['conv1']['threshold']}u\n"
            f"#define LENET5_TH_CONV2 {layers['conv2']['threshold']}u\n"
            f"#define LENET5_TH_FC1   {layers['fc1']['threshold']}u\n"
            f"#define LENET5_TH_FC2   {layers['fc2']['threshold']}u\n"
            f"#define LENET5_TH_FC3   {layers['fc3']['threshold']}u\n\n"
            f"#define LENET5_SUMMAX_CONV1 {layers['conv1']['sum_max']}u\n"
            f"#define LENET5_SUMMAX_CONV2 {layers['conv2']['sum_max']}u\n"
            f"#define LENET5_SUMMAX_FC1   {layers['fc1']['sum_max']}u\n"
            f"#define LENET5_SUMMAX_FC2   {layers['fc2']['sum_max']}u\n"
            f"#define LENET5_SUMMAX_FC3   {layers['fc3']['sum_max']}u\n\n"
            "typedef struct {\n"
            "    uint16_t input_nz_offset;\n"
            "    uint16_t input_nz_count;\n"
            "    uint8_t expected_counts[10];\n"
            "    uint8_t expected_class;\n"
            "    uint8_t label;\n"
            "    uint16_t test_index;\n"
            "} v2b_lenet5_sample_t;\n\n"
            "extern const uint16_t lenet5_input_nz_indices[LENET5_TOTAL_INPUT_NZ];\n"
            "extern const uint32_t lenet5_input_nz_words[LENET5_TOTAL_INPUT_NZ];\n"
            "extern const uint16_t lenet5_conv1_offsets[];\n"
            "extern const uint8_t  lenet5_conv1_entries[];\n"
            "extern const uint16_t lenet5_conv2_offsets[];\n"
            "extern const uint8_t  lenet5_conv2_entries[];\n"
            "extern const uint16_t lenet5_fc1_offsets[];\n"
            "extern const uint8_t  lenet5_fc1_entries[];\n"
            "extern const uint16_t lenet5_fc2_offsets[];\n"
            "extern const uint8_t  lenet5_fc2_entries[];\n"
            "extern const uint16_t lenet5_fc3_offsets[];\n"
            "extern const uint8_t  lenet5_fc3_entries[];\n"
            "extern const v2b_lenet5_sample_t golden_lenet5[LENET5_NUM_SAMPLES];\n\n"
            "#endif /* GOLDEN_LENET5_H */\n"
        )

    with OUT_SRC.open("w", encoding="ascii", newline="\n") as src:
        src.write(
            "/* AUTOGENERATED by fw/v2_e203_smoke/scripts/gen_lenet5_header.py - do not hand-edit. */\n"
            "#include \"golden_lenet5.h\"\n\n"
        )

        src.write(
            f"const uint16_t lenet5_input_nz_indices[{len(sparse_inputs_idx)}] = {{\n"
            f"{fmt_u16_array(sparse_inputs_idx)}\n"
            "};\n\n"
        )
        src.write(
            f"const uint32_t lenet5_input_nz_words[{len(sparse_inputs_words)}] = {{\n"
            f"{fmt_u32_array(sparse_inputs_words)}\n"
            "};\n\n"
        )

        emit_sparse_arrays(src, layers["conv1"], "conv1")
        emit_sparse_arrays(src, layers["conv2"], "conv2")
        emit_sparse_arrays(src, layers["fc1"], "fc1")
        emit_sparse_arrays(src, layers["fc2"], "fc2")
        emit_sparse_arrays(src, layers["fc3"], "fc3")

        src.write(f"const v2b_lenet5_sample_t golden_lenet5[{num_samples}] = {{\n")
        for offset, nz_count, counts, pred, label, test_index in sample_meta:
            src.write("  {\n")
            src.write(f"    .input_nz_offset = {offset}u,\n")
            src.write(f"    .input_nz_count = {nz_count}u,\n")
            src.write("    .expected_counts = {\n")
            src.write(fmt_u8_array(counts, per_line=10))
            src.write("\n    },\n")
            src.write(f"    .expected_class = {pred}u,\n")
            src.write(f"    .label = {label}u,\n")
            src.write(f"    .test_index = {test_index}u,\n")
            src.write("  },\n")
        src.write("};\n")

    print(f"[gen_lenet5_header] wrote {OUT_HDR}")
    print(f"[gen_lenet5_header] wrote {OUT_SRC}")
    print(f"[gen_lenet5_header] total_input_nz={len(sparse_inputs_idx)}")
    for layer_name in ("conv1", "conv2", "fc1", "fc2", "fc3"):
        _, entries = collect_sparse_entries(layers[layer_name])
        print(f"[gen_lenet5_header] {layer_name}: nz={len(entries) // 3}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
