../rtl/top/snn_soc_pkg.sv
../rtl/bus/bus_simple_if.sv
../rtl/bus/bus_interconnect.sv
../rtl/mem/sram_simple.sv
../rtl/mem/sram_simple_dp.sv
../rtl/mem/fifo_sync.sv
../rtl/reg/reg_bank.sv
../rtl/reg/fifo_regs.sv
../rtl/dma/dma_engine.sv
../rtl/snn/dac_ctrl.sv
../rtl/snn/adc_ctrl.sv
../rtl/snn/lif_neurons.sv
../rtl/snn/cim_array_ctrl.sv
../rtl/snn/cim_macro_blackbox.sv
../rtl/periph/uart_stub.sv
../rtl/periph/spi_stub.sv
../rtl/periph/jtag_stub.sv
../rtl/top/snn_soc_top.sv
../tb/tb_lib/bus_master_tasks.sv
../tb/top_tb.sv
