../rtl/top/snn_soc_pkg.sv
../rtl/bus/bus_simple_if.sv
../rtl/bus/bus_interconnect.sv
../rtl/bus/icb_err_slave.sv
../rtl/bus/icb2simple_bridge.sv
../rtl/mem/sram_simple.sv
../rtl/mem/sram_simple_dp.sv
../rtl/mem/fifo_sync.sv
../rtl/reg/reg_bank.sv
../rtl/reg/fifo_regs.sv
../rtl/dma/dma_engine.sv
../rtl/snn/dac_ctrl.sv
../rtl/snn/adc_ctrl.sv
../rtl/snn/lif_neurons.sv
../rtl/snn/lif_neuron_alu.sv
../rtl/snn/spike_feedback.sv
../rtl/snn/layer_sequencer.sv
../rtl/snn/cim_array_ctrl.sv
../rtl/snn/wl_mux_wrapper.sv
../rtl/snn/cim_macro_blackbox.sv
../rtl/snn/cim_program_ctrl.sv
../rtl/snn/cim_macro_arbiter.sv
../rtl/periph/uart_ctrl.sv
../rtl/periph/spi_ctrl.sv
../rtl/periph/jtag_mem_loader.sv
../rtl/top/e203_min_wrap.sv
../rtl/top/snn_soc_top.sv
../tb/multilayer_scan_ext_tb.sv
