`timescale 1ns/1ps
//===========================================================================
// fpga/boards/zcu102/snn_soc_fpga_top.sv
//
// ZCU102 PL top wrapper for feature/main-fpga-e203.
// E203 RISC-V soft-core runs in PL fabric, boots from BRAM pre-loaded
// with e203_fpga_smoke firmware (INSTR_INIT_FILE parameter).
//
// Clock: USER_SI570 300 MHz differential (AL8/AL7) → MMCM → 50 MHz
// Reset: btn_rst (AM13) | !mmcm_locked, 2-FF sync release
// UART:  PMOD J55 A20 (TX from FPGA) / B20 (RX to FPGA), 115200 8N1
//        Requires external USB-TTL adapter (3.3V LVCMOS33)
//
// Firmware PASS tags on UART (115200 8N1):
//   FPGA_E203_BOOT_UART_PASS
//   FPGA_E203_PROGRAM_ERASE_WRITE_PASS
//   FPGA_E203_PROGRAMMED_INFERENCE_PASS
//===========================================================================
module snn_soc_fpga_top #(
  // Absolute path to firmware hex generated by gen_bram_init.py.
  // Set by build_e203_demo.tcl at synthesis time via verilog_define or parameter.
  parameter        INSTR_INIT_FILE = ""
) (
  // 300 MHz USER_SI570 differential clock (ZCU102 bank J: AL8/AL7)
  input  logic sys_clk_p,
  input  logic sys_clk_n,

  // Push-button reset: GPIO_SW_C (AM13, active-high)
  input  logic btn_rst,

  // UART — PMOD J55 (A20=TX, B20=RX)
  output logic uart_txd,
  input  logic uart_rxd,

  // LEDs: [0]=heartbeat [1]=MMCM locked [2]=busy/SoC running [3]=spare
  output logic [3:0] led
);
  import snn_soc_pkg::*;

  // -------------------------------------------------------------------------
  // Clock: IBUFDS + MMCME4_ADV (300 MHz → 50 MHz)
  //   VCO = 300 × 4 = 1200 MHz   → CLKOUT0 ÷ 24 = 50 MHz
  // -------------------------------------------------------------------------
  logic sys_clk_ibuf;
  logic clk_fb;
  logic clk_50m_raw;
  logic clk_50m;
  logic mmcm_locked;

  IBUFDS #(
    .DIFF_TERM    ("TRUE"),
    .IBUF_LOW_PWR ("FALSE")
  ) u_ibufds (
    .O  (sys_clk_ibuf),
    .I  (sys_clk_p),
    .IB (sys_clk_n)
  );

  MMCME4_ADV #(
    .CLKIN1_PERIOD    (3.333),   // 300 MHz
    .CLKFBOUT_MULT_F  (4.0),     // VCO = 1200 MHz
    .CLKOUT0_DIVIDE_F (24.0),    // 1200 / 24 = 50 MHz
    .DIVCLK_DIVIDE    (1),
    .BANDWIDTH        ("OPTIMIZED"),
    .CLKOUT0_DUTY_CYCLE(0.5)
  ) u_mmcm (
    .CLKIN1        (sys_clk_ibuf),
    .CLKIN2        (1'b0),
    .CLKINSEL      (1'b1),
    .CLKFBIN       (clk_fb),
    .CLKFBOUT      (clk_fb),
    .CLKFBOUTB     (),
    .CLKOUT0       (clk_50m_raw),
    .CLKOUT0B      (),
    .CLKOUT1       (), .CLKOUT1B (),
    .CLKOUT2       (), .CLKOUT2B (),
    .CLKOUT3       (), .CLKOUT3B (),
    .CLKOUT4       (),
    .CLKOUT5       (),
    .CLKOUT6       (),
    .LOCKED        (mmcm_locked),
    .PWRDWN        (1'b0),
    .RST           (btn_rst),
    .DADDR         (7'd0),
    .DCLK          (1'b0),
    .DEN           (1'b0),
    .DWE           (1'b0),
    .DI            (16'd0),
    .DO            (),
    .DRDY          (),
    .PSCLK         (1'b0),
    .PSEN          (1'b0),
    .PSINCDEC      (1'b0),
    .PSDONE        (),
    .CDDCREQ       (1'b0),
    .CDDCDONE      (),
    .CLKINSTOPPED  (),
    .CLKFBSTOPPED  ()
  );

  BUFG u_bufg (
    .I (clk_50m_raw),
    .O (clk_50m)
  );

  // -------------------------------------------------------------------------
  // Reset: async assert on !mmcm_locked | btn_rst, sync release on clk_50m
  // -------------------------------------------------------------------------
  logic rst_n_raw;
  logic [1:0] rst_sync;
  logic rst_n;

  assign rst_n_raw = mmcm_locked & ~btn_rst;

  always_ff @(posedge clk_50m or negedge rst_n_raw) begin
    if (!rst_n_raw) rst_sync <= 2'b00;
    else            rst_sync <= {rst_sync[0], 1'b1};
  end
  assign rst_n = rst_sync[1];

  // -------------------------------------------------------------------------
  // SoC instantiation
  //   ENABLE_E203=1          : E203 RISC-V soft-core (boots from INSTR_SRAM)
  //   ENABLE_PROGRAM_MODE=1  : cim_program_ctrl + cim_macro_arbiter active
  //   INSTR_INIT_FILE        : firmware hex pre-loaded into INSTR_SRAM BRAM
  // -------------------------------------------------------------------------
  // Tie-off unused external CIM interface (no ext CIM on FPGA)
  logic [7:0]  wl_data_ext_nc;
  logic [2:0]  wl_group_sel_ext_nc;
  logic        wl_latch_ext_nc;
  logic        cim_start_ext_nc;
  logic [4:0]  bl_sel_ext_nc;

  snn_soc_top #(
    .ENABLE_E203              (1'b1),
    .ENABLE_EXT_CIM_IF        (1'b0),
    .ENABLE_PROGRAM_MODE      (1'b1),
    .ENABLE_PROGRAM_WEIGHT_MODEL (1'b1),
    .INSTR_INIT_FILE          (INSTR_INIT_FILE)
  ) u_soc (
    .clk            (clk_50m),
    .rst_n          (rst_n),
    .uart_rx        (uart_rxd),
    .uart_tx        (uart_txd),
    // SPI: tied off (E203 firmware does not use SPI flash)
    .spi_cs_n       (),
    .spi_sck        (),
    .spi_mosi       (),
    .spi_miso       (1'b1),
    // JTAG rescue: tied off (JTAG not needed after BRAM init)
    .jtag_tck       (1'b0),
    .jtag_tms       (1'b1),
    .jtag_tdi       (1'b0),
    .jtag_tdo       (),
    // External CIM interface: disconnected
    .wl_data_ext      (wl_data_ext_nc),
    .wl_group_sel_ext (wl_group_sel_ext_nc),
    .wl_latch_ext     (wl_latch_ext_nc),
    .cim_start_ext    (cim_start_ext_nc),
    .cim_done_ext     (1'b0),
    .bl_sel_ext       (bl_sel_ext_nc),
    .bl_data_ext      (8'h00)
  );

  // -------------------------------------------------------------------------
  // LED indicators
  // -------------------------------------------------------------------------
  logic [25:0] heartbeat_cnt;

  always_ff @(posedge clk_50m or negedge rst_n) begin
    if (!rst_n) heartbeat_cnt <= '0;
    else        heartbeat_cnt <= heartbeat_cnt + 1'b1;
  end

  assign led[0] = heartbeat_cnt[25];   // ~0.67 Hz blink
  assign led[1] = mmcm_locked;
  assign led[2] = rst_n;               // high = SoC running
  assign led[3] = 1'b0;

  // Suppress lint on undriven outputs
  wire _unused = &{wl_data_ext_nc, wl_group_sel_ext_nc,
                   wl_latch_ext_nc, cim_start_ext_nc, bl_sel_ext_nc};

endmodule
