/* AUTOGENERATED by fw/v2_e203_smoke/scripts/gen_golden_fashion10.py
 * Source: python_multilayer/results_multilayer/fashion_multilayer_golden/
 * Do not hand-edit. */
#ifndef GOLDEN_FASHION10_H
#define GOLDEN_FASHION10_H

#include <stdint.h>

#define GOLDEN_S0_IN_DIM   196u
#define GOLDEN_S0_OUT_DIM  64u
#define GOLDEN_S1_IN_DIM   64u
#define GOLDEN_S1_OUT_DIM  10u
#define GOLDEN_NUM_SAMPLES 10u

/* 4-bit weight values packed into uint8 (high nibble always zero).
 * Row-major, [in_dim][out_dim] linearised. */
extern const uint8_t golden_s0_w_pos[196 * 64];
extern const uint8_t golden_s0_w_neg[196 * 64];
extern const uint8_t golden_s1_w_pos[64 * 10];
extern const uint8_t golden_s1_w_neg[64 * 10];

typedef struct {
    uint8_t  pixel_196[196];
    int32_t  expected_counts[10];
    uint8_t  expected_class;
} v2b_fashion_sample_t;

extern const v2b_fashion_sample_t golden_fashion10[10];

#endif /* GOLDEN_FASHION10_H */
