# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/SoCDesign/fpga/boards/zcu102/constraints_arm.xdc

# Block Designs: bd/bd_step3_arm/bd_step3_arm.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_step3_arm || ORIG_REF_NAME==bd_step3_arm} -quiet] -quiet

# IP: bd/bd_step3_arm/ip/bd_step3_arm_zynq_ultra_ps_e_0_2/bd_step3_arm_zynq_ultra_ps_e_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_step3_arm_zynq_ultra_ps_e_0_2 || ORIG_REF_NAME==bd_step3_arm_zynq_ultra_ps_e_0_2} -quiet] -quiet

# IP: bd/bd_step3_arm/ip/bd_step3_arm_top_fpga_arm_0_0/bd_step3_arm_top_fpga_arm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_step3_arm_top_fpga_arm_0_0 || ORIG_REF_NAME==bd_step3_arm_top_fpga_arm_0_0} -quiet] -quiet

# IP: bd/bd_step3_arm/ip/bd_step3_arm_xbar_0/bd_step3_arm_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_step3_arm_xbar_0 || ORIG_REF_NAME==bd_step3_arm_xbar_0} -quiet] -quiet

# IP: bd/bd_step3_arm/ip/bd_step3_arm_ps8_0_axi_periph_0/bd_step3_arm_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_step3_arm_ps8_0_axi_periph_0 || ORIG_REF_NAME==bd_step3_arm_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/bd_step3_arm/ip/bd_step3_arm_rst_ps8_0_49M_0/bd_step3_arm_rst_ps8_0_49M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_step3_arm_rst_ps8_0_49M_0 || ORIG_REF_NAME==bd_step3_arm_rst_ps8_0_49M_0} -quiet] -quiet

# IP: bd/bd_step3_arm/ip/bd_step3_arm_rst_step3_0_0/bd_step3_arm_rst_step3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_step3_arm_rst_step3_0_0 || ORIG_REF_NAME==bd_step3_arm_rst_step3_0_0} -quiet] -quiet

# IP: bd/bd_step3_arm/ip/bd_step3_arm_rst_inv_0_0/bd_step3_arm_rst_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_step3_arm_rst_inv_0_0 || ORIG_REF_NAME==bd_step3_arm_rst_inv_0_0} -quiet] -quiet

# IP: bd/bd_step3_arm/ip/bd_step3_arm_const_one_0_0/bd_step3_arm_const_one_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_step3_arm_const_one_0_0 || ORIG_REF_NAME==bd_step3_arm_const_one_0_0} -quiet] -quiet

# IP: bd/bd_step3_arm/ip/bd_step3_arm_const_uart_rx_1_0/bd_step3_arm_const_uart_rx_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_step3_arm_const_uart_rx_1_0 || ORIG_REF_NAME==bd_step3_arm_const_uart_rx_1_0} -quiet] -quiet

# IP: bd/bd_step3_arm/ip/bd_step3_arm_const_spi_miso_0_0/bd_step3_arm_const_spi_miso_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_step3_arm_const_spi_miso_0_0 || ORIG_REF_NAME==bd_step3_arm_const_spi_miso_0_0} -quiet] -quiet

# IP: bd/bd_step3_arm/ip/bd_step3_arm_auto_ds_0/bd_step3_arm_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_step3_arm_auto_ds_0 || ORIG_REF_NAME==bd_step3_arm_auto_ds_0} -quiet] -quiet

# IP: bd/bd_step3_arm/ip/bd_step3_arm_auto_pc_0/bd_step3_arm_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_step3_arm_auto_pc_0 || ORIG_REF_NAME==bd_step3_arm_auto_pc_0} -quiet] -quiet

# XDC: e:/VivadoProject/project_5/project_5.gen/sources_1/bd/bd_step3_arm/bd_step3_arm_ooc.xdc
