`timescale 1ns/1ps
//======================================================================
// tb/boot_rom_tb.sv
//
// Standalone smoke test for rtl/mem/boot_rom.sv:
//   T1 — INIT_FILE="" → all reads return 0
//   T2 — INIT_FILE loaded via $readmemh → reads return expected words
//   T3 — writes are ignored (rdata must not change after a write)
//   T4 — SIZE_BYTES edge sweep: 4 / 8 / 16 / 32 / 4096 bytes
//
// Pass tag: BOOT_ROM_TB_PASS
//======================================================================

module boot_rom_tb;
  // Init file is pre-generated by run_boot_rom.sh before vvp starts so
  // that the DUT's initial-block $readmemh sees the file at time 0.
  localparam string INIT_HEX_1 = "boot_rom_init_1.hex";
  localparam string INIT_HEX_2 = "boot_rom_init_2.hex";
  localparam string INIT_HEX_4 = "boot_rom_init_4.hex";
  localparam string INIT_HEX_8 = "boot_rom_init_8.hex";

  // Test signals
  logic        clk;
  logic        rst_n;
  logic        req_valid;
  logic        req_write;
  logic [31:0] req_addr;
  logic [31:0] req_wdata;
  logic [3:0]  req_wstrb;
  logic [31:0] rdata_empty;
  logic [31:0] rdata_init;
  logic [31:0] rdata_4b;
  logic [31:0] rdata_8b;
  logic [31:0] rdata_16b;
  logic [31:0] rdata_4096_empty;

  integer pass_count = 0;
  integer fail_count = 0;

  task automatic expect_word(input logic [31:0] got, input logic [31:0] want, input string label);
    if (got === want) begin
      $display("[PASS] %s: got=0x%08h", label, got);
      pass_count++;
    end else begin
      $display("[FAIL] %s: got=0x%08h want=0x%08h", label, got, want);
      fail_count++;
    end
  endtask

  // DUT A — no INIT_FILE, should read all zeros
  boot_rom #(.SIZE_BYTES(32), .INIT_FILE("")) u_rom_empty (
    .clk(clk), .rst_n(rst_n),
    .req_valid(req_valid), .req_write(req_write), .req_addr(req_addr),
    .req_wdata(req_wdata), .req_wstrb(req_wstrb),
    .rdata(rdata_empty)
  );

  // DUT B — INIT_FILE loaded, 32 bytes (8 words)
  boot_rom #(.SIZE_BYTES(32), .INIT_FILE(INIT_HEX_8)) u_rom_init (
    .clk(clk), .rst_n(rst_n),
    .req_valid(req_valid), .req_write(req_write), .req_addr(req_addr),
    .req_wdata(req_wdata), .req_wstrb(req_wstrb),
    .rdata(rdata_init)
  );

  // Edge-size DUTs requested by review: 4 / 8 / 16 / 32 / 4096 bytes.
  // The 4-byte instance is the important $clog2(1)=0 corner.
  boot_rom #(.SIZE_BYTES(4), .INIT_FILE(INIT_HEX_1)) u_rom_4b (
    .clk(clk), .rst_n(rst_n),
    .req_valid(req_valid), .req_write(req_write), .req_addr(req_addr),
    .req_wdata(req_wdata), .req_wstrb(req_wstrb),
    .rdata(rdata_4b)
  );

  boot_rom #(.SIZE_BYTES(8), .INIT_FILE(INIT_HEX_2)) u_rom_8b (
    .clk(clk), .rst_n(rst_n),
    .req_valid(req_valid), .req_write(req_write), .req_addr(req_addr),
    .req_wdata(req_wdata), .req_wstrb(req_wstrb),
    .rdata(rdata_8b)
  );

  boot_rom #(.SIZE_BYTES(16), .INIT_FILE(INIT_HEX_4)) u_rom_16b (
    .clk(clk), .rst_n(rst_n),
    .req_valid(req_valid), .req_write(req_write), .req_addr(req_addr),
    .req_wdata(req_wdata), .req_wstrb(req_wstrb),
    .rdata(rdata_16b)
  );

  boot_rom #(.SIZE_BYTES(4096), .INIT_FILE("")) u_rom_4096_empty (
    .clk(clk), .rst_n(rst_n),
    .req_valid(req_valid), .req_write(req_write), .req_addr(req_addr),
    .req_wdata(req_wdata), .req_wstrb(req_wstrb),
    .rdata(rdata_4096_empty)
  );

  initial begin
    clk = 1'b0;
    forever #10 clk = ~clk;  // 50 MHz
  end

  initial begin
    $dumpfile("waves/boot_rom.vcd");
    $dumpvars(0, boot_rom_tb);

    rst_n      = 1'b0;
    req_valid  = 1'b0;
    req_write  = 1'b0;
    req_addr   = 32'h0;
    req_wdata  = 32'h0;
    req_wstrb  = 4'h0;
    repeat (5) @(posedge clk);
    rst_n = 1'b1;
    repeat (2) @(posedge clk);

    // ── T1: INIT_FILE="" → reads return 0 ──────────────────────────
    req_valid = 1'b1;
    for (int i = 0; i < 8; i++) begin
      req_addr = i * 4;
      @(posedge clk);
      #1; // wait for combinational rdata to settle
      expect_word(rdata_empty, 32'h0000_0000, $sformatf("T1 empty[%0d]", i));
    end

    // ── T2: INIT_FILE loaded → reads return expected words ─────────
    for (int i = 0; i < 8; i++) begin
      req_addr = i * 4;
      @(posedge clk);
      #1;
      case (i)
        0: expect_word(rdata_init, 32'hDEADBEEF, "T2 init[0]");
        1: expect_word(rdata_init, 32'hCAFEBABE, "T2 init[1]");
        2: expect_word(rdata_init, 32'h0000_0013, "T2 init[2]");
        3: expect_word(rdata_init, 32'h0000_0001, "T2 init[3]");
        4: expect_word(rdata_init, 32'h1111_2222, "T2 init[4]");
        5: expect_word(rdata_init, 32'h3333_4444, "T2 init[5]");
        6: expect_word(rdata_init, 32'h5555_6666, "T2 init[6]");
        7: expect_word(rdata_init, 32'h7777_8888, "T2 init[7]");
      endcase
    end

    // ── T3: writes are ignored (rdata at addr 0 stays the same) ───
    req_addr  = 32'h0;
    req_write = 1'b1;
    req_wdata = 32'hBAD0_BAD0;
    req_wstrb = 4'hF;
    repeat (3) @(posedge clk);
    req_write = 1'b0;
    req_wstrb = 4'h0;
    #1;
    expect_word(rdata_init, 32'hDEADBEEF, "T3 init[0] after write (unchanged)");

    // ── T4: SIZE_BYTES edge sweep ────────────────────────────────
    req_valid = 1'b1;
    req_write = 1'b0;

    req_addr = 32'h0;
    @(posedge clk); #1;
    expect_word(rdata_4b, 32'h0BAD_C0DE, "T4 size4 addr0");

    // SIZE_BYTES=4 has exactly one word.  Higher addresses alias to word 0
    // in this simple local ROM aperture instead of indexing rom[1] out of range.
    req_addr = 32'h4;
    @(posedge clk); #1;
    expect_word(rdata_4b, 32'h0BAD_C0DE, "T4 size4 addr4 clamps");

    req_addr = 32'h0;
    @(posedge clk); #1;
    expect_word(rdata_8b, 32'h1111_0000, "T4 size8 word0");
    req_addr = 32'h4;
    @(posedge clk); #1;
    expect_word(rdata_8b, 32'h2222_0000, "T4 size8 word1");

    req_addr = 32'hC;
    @(posedge clk); #1;
    expect_word(rdata_16b, 32'h4444_0000, "T4 size16 word3");

    req_addr = 32'hFFC;
    @(posedge clk); #1;
    expect_word(rdata_4096_empty, 32'h0000_0000, "T4 size4096 last word empty");

    $display("");
    $display("=== Results: %0d PASS, %0d FAIL ===", pass_count, fail_count);
    if (fail_count == 0) begin
      $display("BOOT_ROM_TB_PASS");
    end else begin
      $display("BOOT_ROM_TB_FAIL");
      $fatal(1);
    end
    $finish;
  end

endmodule
